### ISSUE TITLE
How to use in a typical web project with npm modules?

### ISSUE THREAD

**Issue by magwo** [MaxGraey/as-string-sink#14]
Hello and thanks for a very interesing project! I'm very interested in the potential performance improvements and the reduced memory churn.

I'm trying to use the as-string-sink in an Angular project generated by the Angular CLI (ng).

After installing using `npm install as-string-sink`, importing and trying to use `new StringSink` in code I get errors about types like i32 and usize not being found. I think this means that my project is trying to parse the assemblyscript .ts file as regular TypeScript?

Looking at the as-string-sink folder in node_modules I'm seeing no binary wasm files installed. I only see the source code. Is this expected?

I'm not really sure how to use the as-string-sink library. Do I need to set up an assemblyscript build script in my project? And also load the wasm files in the browser somehow? I'm under the impression that wasm files would be published to npm by this project's build pipeline. I'm a little confused.

**Comment by MaxGraey** [comment]
Hi! Sorry that you may have been misled that this code can be used in regular TypeScript. This module is made for AssemblyScript lang (subset of Typescript which compiles to WebAssembly). So you can't use it as is in a TS environment. For this, you will have to make an interop between JS and Wasm. Such an interop completely negates the performance gain that StringSink gives, so I don't recommend looking in this direction. 

The team of V8 engine is already experimenting with replacing rope data structure for concatenated strings with “string builders” similar to this StringSink. And maybe v8 already supports this under some experimental flag?

Meanwhile, there is only one hack that can potentially speed up rope-based strings in V8 - is string flattening:
https://www.npmjs.com/package/flatstr

which is simply do this:
```ts
export function flatstr(str: string): string {
  str | 0
  return str
}
```

**Comment by magwo** [comment]
Alright, thanks for the clarification.

However, if this library shouldn't be used in JavaScript environments, why is it published to NPM? Isn't NPM primarily for Node(JavaScript) packages?

**Comment by magwo** [comment]
Aahaaa I think I get it now. The export class statement is meant for consumption from other AssemblyScript files? So exporting classes works within an AssemblyScript project, but not when building to wasm in the end?

**Comment by MaxGraey** [comment]
> Aahaaa I think I get it now. The export class statement is meant for consumption from other AssemblyScript files? So exporting classes works within an AssemblyScript project, but not when building to wasm in the end?

Yes. Class exporting works only within AS env. WebAssembly supports only function exporting outside main module (wasm module)

**Comment by magwo** [comment]
Yeah thanks! My use case is to rebuild a very large (~500 KB) dynamic SVG `path` string at full framerate (60 fps).

Obviously this is stretching the capabilities of SVG. But I would like to take it as far as possible by ensuring good performance, and good overhead for a reduced-complexity scenario.

At the moment it seems like the string concatenation of hundreds of thousands of strings at 60 fps is a pretty big performance bottleneck, especially because it is causing big memory churn, causing Minor GC to take up about 10 ms every frame.

I think that a proper buffer-based string sink such as yours, or a similar string builder would give big performance improvements - primarily because I could reuse the buffer objects between frames and thus avoid lots of memory allocation, churn and garbage collection.

I have not seen any significant improvements by switching to Array.join or ''.concat, from the current implementation that is using template literals and basic string `+=`.

Do you have any ideas or suggestions on how to get my hands on a string sink/buffer that can be used from JavaScript in a browser? Are you sure that the js/wasm interop would kill performance in such a scenario?

**Comment by MaxGraey** [comment]
If you have performance bottlenecks, it makes sense to switch to WebAssembly using AssemblyScript or Rust langs. But you should keep heavily computed logic inside WebAssembly and reduce interop between js and wasm to minimum, especially for strings which not only copy but also required some encoding during interop.

**Comment by magwo** [comment]
Thanks!
