### ISSUE TITLE
Build problem: WARNING AS235: Only variables, functions and enums become WebAssembly module exports.

### ISSUE THREAD

**Issue by magwo** [MaxGraey/as-string-sink#15]
Hello!

Looking at the code in assembly/index.ts it appears to export a class - StringSink.

However, when I build it (optimized) with assemblyscript 27.27, I get this warning:

`WARNING AS235: Only variables, functions and enums become WebAssembly module exports.`

This also appears to result in fairly empty outputted binary build files.

Did exporting classes work in previous versions of AssemblyScript?

**Comment by MaxGraey** [comment]
https://github.com/MaxGraey/as-string-sink/issues/14#issuecomment-2157677976

**Comment by magwo** [comment]
@MaxGraey I think you misunderstood. I cloned this repo and was trying to build this actual project to build a wasm file (with some upgraded dependencies).

Did exporting of a class work previously? It doesn't appear to work with AssemblyScript 0.27.27.
