### ISSUE TITLE
The performance between ArrayBuffer and StaticArray<u8>

### ISSUE THREAD

**Issue by yjhmelody** [MaxGraey/as-string-sink#3]
Have you tried to compare the performance between ArrayBuffer and StaticArray<u8>(and heap.alloc)?

**Comment by MaxGraey** [comment]
No, but It should has no differences. `heap.alloc` can't be used here due to need call `heap.free` explicitly when StringSink object no need anymore

**Comment by yjhmelody** [comment]
Ok, I got it. Thanks!
